import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { getCurrentUser } from "@/lib/auth/tokens";

// Simple in-memory zip creation (for demo - in production use archiver or similar)
function createZipBuffer(files: Array<{ path: string; content: string }>, readme: string): Uint8Array {
  // For simplicity, we'll create a simple concatenated format
  // In production, use a proper zip library like 'archiver'

  const encoder = new TextEncoder();
  const chunks: Uint8Array[] = [];

  // Add README
  const readmeBytes = encoder.encode(`--- README.md ---\n${readme}\n\n`);
  chunks.push(readmeBytes);

  // Add each file
  for (const file of files) {
    const header = encoder.encode(`--- ${file.path} ---\n`);
    const content = encoder.encode(file.content);
    const footer = encoder.encode(`\n\n`);
    chunks.push(header);
    chunks.push(content);
    chunks.push(footer);
  }

  // Combine all chunks
  const totalLength = chunks.reduce((acc, chunk) => acc + chunk.length, 0);
  const result = new Uint8Array(totalLength);
  let offset = 0;
  for (const chunk of chunks) {
    result.set(chunk, offset);
    offset += chunk.length;
  }

  return result;
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ projectId: string }> }
) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { projectId } = await params;

    const project = await prisma.project.findFirst({
      where: {
        id: projectId,
        userId: user.id,
      },
      include: {
        files: true,
        assets: {
          where: { status: "completed" },
        },
      },
    });

    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    // Create README content
    const readme = `# ${project.name}

Created with AI Game Maker Studio

## Setup

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Run the development server:
   \`\`\`bash
   npm run dev
   \`\`\`

3. Open http://localhost:3000 in your browser

## Project Structure

${project.files.map((f) => `- ${f.path}`).join("\n")}

## Assets

${
  project.assets.length > 0
    ? project.assets.map((a) => `- ${a.name}: ${a.glbUrl || "pending"}`).join("\n")
    : "No 3D assets generated yet."
}

## License

This project was created by you and you own all rights to it.

---
Generated by AI Game Maker Studio
`;

    // Create the export bundle
    const files = project.files.map((f) => ({
      path: f.path,
      content: f.content,
    }));

    const zipBuffer = createZipBuffer(files, readme);

    console.log(`[api/projects/[id]/export] Exported project ${projectId}`);

    return new NextResponse(zipBuffer, {
      headers: {
        "Content-Type": "text/plain",
        "Content-Disposition": `attachment; filename="${project.name.replace(/[^a-z0-9]/gi, "_")}_export.txt"`,
      },
    });
  } catch (error) {
    console.error("[api/projects/[id]/export] Error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
